steps:
  - name: 'europe-west3-docker.pkg.dev/pocagrochocinski/docker-repo/maven-user:latest'
    args:
      - '-c'
      - |
        echo "copy project"
        cp -r /workspace/. /home/jenkins/wildfly-core/
        cd /home/jenkins/wildfly-core/
        echo "current directory: $(pwd)"
        echo "build and test"
        mvn clean install -B -Puse-gcp-artifact-registry -DallTests -Drelease=true -ntp
        mvn deploy -B -Puse-gcp-artifact-registry -DskipTests -Drelease=true -ntp
    entrypoint: bash
timeout: 14400s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
